import React from 'react';
import styles from './Contacto.module.css';
import ContactForm from '@/components/ContactForm/ContactForm';
import Image from 'next/image';

export const metadata = {
  title: 'Formula Hogar - Contacto',
  description: 'Generated by create next app',
};

const Contacto = () => {
  return (
    <div className={styles.contacto_container}>
      <Image
        className={styles.fondo_contacto1}
        src="/images/productos/LogosAromas/logoOriginal.png"
        alt="contacto"
        width={400}
        height={500}
      />
      <Image
        className={styles.fondo_contacto2}
        src="/images/productos/LogosAromas/lineadeproductos2.png"
        alt="contacto"
        width={600}
        height={700}
      />
      <ContactForm />
    </div>
  );
};

export default Contacto;
