import React from 'react';

export const metadata = {
  title: 'Formula Hogar - Carrito',
  description: 'Generated by create next app',
};

const Carrito = () => {
  return <div>Carrito</div>;
};

export default Carrito;
