import React from 'react';
import styles from './Pedidos.module.css';
import CardPedidos from '@/components/CardPedidos/CardPedidos';

const productos = [
  {
    id: 1,
    producto: 'Alcohol en Gel',
    precio: '100',
    img_url: '/images/productos/LogosAromas/colores_alcoholgel.png',
    img_thumb: '/images/productos/LogosAromas/colores_alcoholgel.png',
    descripcion:
      'Gel antibacterial sin acción terapéutica, a base de alcohol etílico, incoloro y sin perfume. Fórmula con alto contenido de alcohol que elimina eficazmente el 99.9% de bacterias y gérmenes sin necesidad de enjuague. Su textura en gel permite una aplicación fácil y rápida, dejando las manos limpias y frescas sin sensación pegajosa. Enriquecido con agentes humectantes para proteger la piel, es ideal para el uso diario en el hogar, la oficina o en movimiento.',
    oferta: true,
  },
  {
    id: 2,
    producto: 'Antigrasa',
    precio: '100',
    img_url: '/images/productos/LogosAromas/colores_antigrasa.png',
    img_thumb: '/images/productos/LogosAromas/colores_antigrasa.png',
    descripcion:
      'Máxima protección y alto poder de desinfección para baños, pisos, azulejos, mesadas, vajillas, baldes de residuos, etc. Limpia y desinfecta a fondo. Apto para remover manchas.',
    oferta: false,
  },
  {
    id: 3,
    producto: 'Cera Acrilica',
    precio: '100',
    img_url: '/images/productos/LogosAromas/colores_antigrasa.png',
    img_thumb: '/images/productos/LogosAromas/colores_antigrasa.png',
    descripcion:
      'Otorga a sus pisos brillo instantáneo y resistente. Fácil de aplicar, dejando un agradable perfume. Utilizar con carro o mopa. Aplicar puro o diluido hasta una tercera parte sobre el piso.',
    oferta: false,
  },
  {
    id: 4,
    producto: 'Lavandina',
    precio: '100',
    img_url: '/images/productos/LogosAromas/colores_lavanidina.png',
    img_thumb: '/images/productos/LogosAromas/colores_lavanidina.png',
    descripcion:
      'Máxima protección y alto poder de desinfección para baños, pisos, azulejos, mesadas, vajillas, baldes de residuos, etc. Limpia y desinfecta a fondo. Apto para remover manchas.',
    oferta: true,
  },
  {
    id: 5,
    producto: 'Limpiador de Pisos',
    precio: '100',
    img_url: '/images/productos/LogosAromas/colores_limpiadordepisos.png',
    img_thumb: '/images/productos/LogosAromas/colores_limpiadordepisos.png',
    descripcion:
      'Líquido aromatizante, desodoriza eliminando malos olores. Desinfecta y desengrasa, pisos y superficies lavables. Nuestra fórmula es aplicable en pisos, mosaicos, cerámicos, porcelanatos, baldosas, lajas y plastificados.',
    oferta: false,
  },
  {
    id: 6,
    producto: 'Shampoo para Manos',
    precio: '100',
    img_url: '/images/productos/LogosAromas/colores_shampoomanoros.png',
    img_thumb: '/images/productos/LogosAromas/colores_shampoomanoros.png',
    descripcion:
      'El shampoo para manos o jabón líquido esta formulado para el lavado de manos. Su exclusiva fórmula equilibra limpieza y desengrasa con humectación para no resecar la piel y dejarla suave con una agradable fragancia recomendada para una ideal higiene, realizando una desinfección profunda y protegiéndola de agentes extraños.',
    oferta: false,
  },
  {
    id: 7,
    producto: 'Suavizante',
    precio: '100',
    img_url: '/images/productos/LogosAromas/colores_suavizante.png',
    img_thumb: '/images/productos/LogosAromas/colores_suavizante.png',
    descripcion:
      'Tu ropa y la de tu familia permanecerán perfumadas, suaves y cómodas. Resaltando sus olores y facilitando el planchado de las prendas. Apto para el lavado de prendas semi delicadas y delicadas, ropa blanca, toallas, manteles, etc. Dejando un agradable y persistente aroma residual. Evita la electricidad estática en fibras sintéticas.',
    oferta: false,
  },
  {
    id: 8,
    producto: 'Shampoo para Autos',
    precio: '100',
    img_url: '/images/productos/LogosAromas/colores_shampooautos.png',
    img_thumb: '/images/productos/LogosAromas/colores_shampooautos.png',
    descripcion:
      'Lavacoche siliconado apto para todo tipo de pinturas. Ultra brillo + Resaltador de color. Fórmula avanzada diseñada para eliminar suciedad, polvo y residuos sin dañar la pintura ni la capa protectora del vehículo. Su acción espumante facilita el lavado, proporcionando un acabado brillante y sin marcas. Ideal para uso doméstico y profesional, asegurando una limpieza profunda con el máximo cuidado.',
    oferta: true,
  },
];

export const metadata = {
  title: 'Formula Hogar - Pedidos',
  description: 'Generated by create next app',
};

const Pedidos = () => {
  return (
    <div className={styles.pedidos_container}>
      <div className={styles.productos_container}>
        {productos.map((producto) => {
          return <CardPedidos key={producto.id} producto={producto} />;
        })}
      </div>
    </div>
  );
};

export default Pedidos;
