import styles from './CardInformacion.module.css';
import Link from 'next/link';
import Image from 'next/image';

const CardInformacion = () => {
  return (
    <div className={styles.card_informacion_container}>
      <div className={styles.container_images}>
        <Image
          src="/images/deslizables/img01.png"
          width={150}
          height={150}
          alt="publicidad"
        />
        <Image
          src="/images/deslizables/img02.png"
          width={150}
          height={150}
          alt="publicidad"
        />
        <Image
          src="/images/deslizables/img03.png"
          width={150}
          height={150}
          alt="publicidad"
        />
        <Image
          src="/images/deslizables/img04.png"
          width={150}
          height={150}
          alt="publicidad"
        />
        <Image
          src="/images/deslizables/img05.png"
          width={150}
          height={150}
          alt="publicidad"
        />
        <Image
          src="/images/deslizables/img06.png"
          width={150}
          height={150}
          alt="publicidad"
        />
        <Image
          src="/images/deslizables/img07.png"
          width={150}
          height={150}
          alt="publicidad"
        />
        <Image
          src="/images/deslizables/img08.png"
          width={150}
          height={150}
          alt="publicidad"
        />
        <Image
          src="/images/deslizables/img09.png"
          width={150}
          height={150}
          alt="publicidad"
        />
        <Image
          src="/images/deslizables/img10.png"
          width={150}
          height={150}
          alt="publicidad"
        />
        <Image
          src="/images/deslizables/img11.png"
          width={150}
          height={150}
          alt="publicidad"
        />
        <Image
          src="/images/deslizables/img12.png"
          width={150}
          height={150}
          alt="publicidad"
        />
        <Image
          src="/images/deslizables/img13.png"
          width={150}
          height={150}
          alt="publicidad"
        />
        <Image
          src="/images/deslizables/img14.png"
          width={150}
          height={150}
          alt="publicidad"
        />
        <Image
          src="/images/deslizables/img15.png"
          width={150}
          height={150}
          alt="publicidad"
        />
        <Image
          src="/images/deslizables/img16.png"
          width={150}
          height={150}
          alt="publicidad"
        />
        <Image
          src="/images/deslizables/img17.png"
          width={150}
          height={150}
          alt="publicidad"
        />
        <Image
          src="/images/deslizables/img18.png"
          width={150}
          height={150}
          alt="publicidad"
        />
        <Image
          src="/images/deslizables/img19.png"
          width={150}
          height={150}
          alt="publicidad"
        />
        <Image
          src="/images/deslizables/img20.png"
          width={150}
          height={150}
          alt="publicidad"
        />
        <Image
          src="/images/deslizables/img21.png"
          width={150}
          height={150}
          alt="publicidad"
        />
        <Image
          src="/images/deslizables/img22.png"
          width={150}
          height={150}
          alt="publicidad"
        />
      </div>
    </div>
  );
};

export default CardInformacion;
