import { Geist, Geist_Mono, Poppins, Bebas_Neue } from 'next/font/google';
import './globals.css';
import NavBar from '@/components/NavBar/NavBar';
import BannerRedesSociales from '@/components/BannerRedesSociales/BannerRedesSociales';
import Footer from '@/components/Footer/Footer';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

const bebasNeue = Bebas_Neue({
  variable: '--font-bebas-neue',
  subsets: ['latin'],
  weight: ['400'],
});

export const metadata = {
  title: 'Formula Hogar',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${bebasNeue.variable}`}
      >
        {/* <BannerRedesSociales /> */}
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
