import React from 'react';
import styles from './Productos.module.css';
import Image from 'next/image';

export const metadata = {
  title: 'Formula Hogar - Productos',
  description: 'Generated by create next app',
};

const Productos = () => {
  return (
    <div className={styles.container}>
      <section className={styles.linea_de_productos}>
        <Image
          className={styles.linea_productos_img1}
          src={'/images/Productos/LogosAromas/lineadeproductos1.png'}
          width={500}
          height={500}
          alt="linea"
        />
        <Image
          className={styles.linea_productos_img2}
          src={'/images/Productos/LogosAromas/lineadeproductos2.png'}
          width={500}
          height={500}
          alt="linea"
        />
        <Image
          className={styles.logo_linea_productos}
          src={'/images/logos/FormulaHogarLogoSinFondo.png'}
          width={460}
          height={150}
          alt="logo"
        />
        <h2>LÍNEA DE PRODUCTOS</h2>
      </section>
      <section className={styles.desodorante_pisos} id="limpiador_de_pisos">
        <Image
          className={styles.desodorante_pisos_logo}
          src={'/images/Productos/LogosAromas/desodorantepisos.png'}
          width={500}
          height={500}
          alt="DesodorantePisos"
        />
        <Image
          className={styles.desodorante_pisos_productos}
          src={'/images/Productos/Layers/DesodorantesParaPisos.png'}
          width={850}
          height={550}
          alt="DesodorantePisos"
        />
        <div className={styles.desodorante_pisos_textos}>
          <h2>Desodorante para Pisos</h2>
          <p>
            Líquido aromatizante, desodoriza eliminando malos olores. Desinfecta
            y desengrasa, pisos y superficies lavables. Nuestra fórmula es
            aplicable en pisos, mosaicos, cerámicos, porcelanatos, baldosas,
            lajas y plastificados.
          </p>
          <Image
            src={'/images/Productos/LogosAromas/colores_desodorantepisos.png'}
            width={350}
            height={350}
            alt="Aromas"
          />
        </div>
      </section>
      <section className={styles.lavandina_concentrada} id="lavandina">
        <Image
          className={styles.lavandina_concentrada_logo}
          src={'/images/Productos/LogosAromas/lavandinaconcentrada.png'}
          width={500}
          height={500}
          alt="Lavandina"
        />
        <Image
          className={styles.lavandina_concentrada_productos}
          src={'/images/Productos/Layers/LavandinaConcentrada.png'}
          width={850}
          height={850}
          alt="DesodorantePisos"
        />
        <div className={styles.lavandina_concentrada_textos}>
          <h2>Lavandina Concentrada</h2>
          <p>
            Máxima protección y alto poder de desinfección para baños, pisos,
            azulejos, mesadas, vajillas, baldes de residuos, etc. Limpia y
            desinfecta a fondo. Apto para remover manchas.
          </p>
          <Image
            src={'/images/Productos/productonocivo.png'}
            width={120}
            height={50}
            alt="Nocivo"
          />
        </div>
      </section>
      <section className={styles.detergente} id="detergente">
        <Image
          className={styles.detergente_logo}
          src={'/images/Productos/LogosAromas/detergente.png'}
          width={500}
          height={500}
          alt="detergente"
        />
        <div className={styles.detergente_imagenes}>
          <Image
            className={styles.limon}
            src={'/images/Productos/LogosAromas/colores_detergentelimon.png'}
            width={130}
            height={130}
            alt="detergente limon"
          />
          <Image
            className={styles.detergente_productos}
            src={'/images/Productos/Layers/Detergentes.png'}
            width={750}
            height={500}
            alt="DesodorantePisos"
          />
          <Image
            className={styles.detergente_original}
            src={'/images/Productos/LogosAromas/colores_detergenteoriginal.png'}
            width={130}
            height={130}
            alt="detergente original"
          />
        </div>
        <div className={styles.detergente_textos}>
          <h2>Detergente</h2>
          <p>
            Detergente formulado con un 10% de materia activa. Ideal para
            desengrasar y limpiar con profundidad sus vajillas, pisos de todo
            tipo, vidrios y baños. La versión original es ideal para uso de
            vajilla en restaurantes, bares, etc.
          </p>
        </div>
      </section>
      <section className={styles.detergente30} id="detergente30">
        <Image
          className={styles.detergente30_logo}
          src={'/images/Productos/LogosAromas/detergente30.png'}
          width={500}
          height={500}
          alt="detergente30%"
        />
        <Image
          className={styles.detergente30_productos}
          src={'/images/Productos/Layers/Detergente30.png'}
          width={850}
          height={850}
          alt="Detergente 30%"
        />
        <div className={styles.detergente30_textos}>
          <h2>Detergente 30%</h2>
          <p>
            Detergente formulado con un 30% de materia activa, ideal para
            desengrasar y limpiar con profundidad sus vajillas, pisos de todo
            tipo, vidrios y baños.
          </p>
        </div>
      </section>
      <section className={styles.detergente15} id="detergente15">
        <Image
          className={styles.detergente15_logo}
          src={'/images/Productos/LogosAromas/detergente30.png'}
          width={500}
          height={500}
          alt="detergente15%"
        />
        <Image
          className={styles.detergente15_productos}
          src={'/images/Productos/Layers/Detergente15.png'}
          width={850}
          height={850}
          alt="Detergente 15%"
        />
        <div className={styles.detergente15_textos}>
          <h2>Detergente 15%</h2>
          <p>
            Detergente formulado con un 15% de materia activa, ideal para
            desengrasar y limpiar con profundidad sus vajillas, pisos de todo
            tipo, vidrios y baños.
          </p>
        </div>
      </section>
      <section className={styles.antigrasa} id="antigrasa">
        <Image
          className={styles.antigrasa_logo}
          src={'/images/Productos/LogosAromas/antigrasa.png'}
          width={500}
          height={500}
          alt="Antigrasa"
        />
        <Image
          className={styles.antigrasa_productos}
          src={'/images/Productos/Layers/Antigrasa.png'}
          width={850}
          height={850}
          alt="Antigrasa"
        />
        <div className={styles.antigrasa_textos}>
          <h2>Antigrasa</h2>
          <p>
            Formulado para eliminar la grasa mas extrema y residuos adheridos
            con facilidad, este producto ofrece una limpieza profunda en
            cocinas, electrodomésticos y superficies industriales. Su fórmula
            concentrada permite un alto rendimiento, garantizando resultados
            óptimos con menor cantidad de producto. Ideal para uso doméstico y
            profesional.
          </p>
        </div>
      </section>
      <section className={styles.desengrasante} id="desengrasante">
        <Image
          className={styles.desengrasante_logo}
          src={'/images/Productos/LogosAromas/desengrasante.png'}
          width={500}
          height={500}
          alt="Desengrasante"
        />
        <Image
          className={styles.desengrasante_productos}
          src={'/images/Productos/Layers/Desengrasantes.png'}
          width={1000}
          height={500}
          alt="Desengrasante"
        />
        <div className={styles.desengrasante_textos}>
          <h2>Desengrasante</h2>
          <div className={styles.hogar}>
            <Image
              src={
                '/images/Productos/LogosAromas/colores_desengrasantehogar.png'
              }
              width={120}
              height={120}
              alt="Desengrasante"
            />
            <p>
              La excelente fórmula del desengrasante permite limpiar con
              profundidad cocinas, paredes, pisos y todo tipo de superficies con
              grasitudes pesadas.
            </p>
          </div>
          <div className={styles.alcalino}>
            <Image
              src={
                '/images/Productos/LogosAromas/colores_desengrasantealcalino.png'
              }
              width={120}
              height={120}
              alt="Desengrasante"
            />
            <p>
              Tambien, nuestro producto alcalino está especialmente formulado
              para remover grasitudes de pisos, paredes, grandes superficies,
              cañería de pvc, maquinaria de materiales duros, aceros
              inoxidables, etc.
            </p>
          </div>
        </div>
      </section>
      <section className={styles.limpiavidrios} id="limpiavidrios">
        <Image
          className={styles.limpiavidrios_logo}
          src={'/images/Productos/LogosAromas/limpiavidrios.png'}
          width={500}
          height={500}
          alt="Limpiavidrios"
        />
        <Image
          className={styles.limpiavidrios_productos}
          src={'/images/Productos/Layers/Limpiavidrios.png'}
          width={850}
          height={850}
          alt="Limpiavidrios"
        />
        <div className={styles.limpiavidrios_textos}>
          <h2>Limpia Vidrios</h2>
          <p>
            Fórmula especializada que elimina polvo, grasa y marcas con rapidez,
            dejando los vidrios y espejos impecables y sin vetas. Su acción de
            secado rápido garantiza una limpieza eficiente y duradera, realzando
            la claridad y el brillo de las superficies. Ideal para ventanas,
            espejos, parabrisas y superficies de cristal, tanto en el hogar como
            en espacios comerciales.
          </p>
        </div>
      </section>
      <section className={styles.shampo_autos} id="shampo_autos">
        <Image
          className={styles.shampo_autos_logo}
          src={'/images/Productos/LogosAromas/shampoautos.png'}
          width={500}
          height={500}
          alt="Shampo Autos"
        />
        <Image
          className={styles.shampo_autos_productos}
          src={'/images/Productos/Layers/ShampoAutos.png'}
          width={1000}
          height={1000}
          alt="Shampo Autos"
        />
        <div className={styles.shampo_autos_textos}>
          <h2>Shampoo para Autos</h2>
          <p>
            Lavacoche siliconado apto para todo tipo de pinturas. Ultra brillo +
            Resaltador de color. Fórmula avanzada diseñada para eliminar
            suciedad, polvo y residuos sin dañar la pintura ni la capa
            protectora del vehículo. Su acción espumante facilita el lavado,
            proporcionando un acabado brillante y sin marcas. Ideal para uso
            doméstico y profesional, asegurando una limpieza profunda con el
            máximo cuidado.
          </p>
        </div>
      </section>
      <section className={styles.jabon_liquido_baja_espuma} id="jabon_liquido">
        <Image
          className={styles.jabon_liquido_baja_espuma_logo}
          src={'/images/Productos/LogosAromas/jabonliquidobajaespuma.png'}
          width={500}
          height={500}
          alt="Jabon Liquido Baja Espuma"
        />
        <Image
          className={styles.jabon_liquido_baja_espuma_productos}
          src={'/images/Productos/Layers/JabonLiquidoBajaEspuma.png'}
          width={1050}
          height={750}
          alt="Jabon Liquido Baja Espuma"
        />
        <div className={styles.jabon_liquido_baja_espuma_textos}>
          <h2>Jabón Líquido Baja Espuma</h2>
          <p>
            Jabón para lavarropas automáticos, fórmula con hp balanceado y con
            propiedades antiespumantes, deja su ropa limpia y con olor a limpio.
          </p>
          <Image
            src={
              '/images/Productos/LogosAromas/colores_jabonliquidobajaespuma.png'
            }
            width={120}
            height={270}
            alt="Jabon Liquido Baja Espuma"
          />
        </div>
      </section>
      <section className={styles.suavizante_ropa} id="suavizante">
        <Image
          className={styles.suavizante_ropa_logo}
          src={'/images/Productos/LogosAromas/suavizanteropa.png'}
          width={500}
          height={500}
          alt="Suavizante Ropa"
        />
        <Image
          className={styles.suavizante_ropa_productos}
          src={'/images/Productos/Layers/SuavizanteRopa.png'}
          width={1000}
          height={650}
          alt="Suavizante Ropa"
        />

        <div className={styles.suavizante_ropa_textos}>
          <h2>Suavizante para Ropa</h2>
          <p>
            Tu ropa y la de tu familia permanecerán perfumadas, suaves y
            cómodas. Resaltando sus olores y facilitando el planchado de las
            prendas. Apto para el lavado de prendas semi delicadas y delicadas,
            ropa blanca, toallas, manteles, etc. Dejando un agradable y
            persistente aroma residual. Evita la electricidad estática en fibras
            sintéticas.
          </p>
          <Image
            src={'/images/Productos/LogosAromas/colores_suavizantepararopa.png'}
            width={410}
            height={125}
            alt="Suavizante Ropa"
          />
        </div>
      </section>
      <section className={styles.shampo_manos} id="shampoo_para_manos">
        <Image
          className={styles.shampo_manos_logo}
          src={'/images/Productos/LogosAromas/shampomanos.png'}
          width={500}
          height={500}
          alt="Shampo Manos"
        />
        <Image
          className={styles.shampo_manos_productos}
          src={'/images/Productos/Layers/ShampoManos.png'}
          width={1000}
          height={650}
          alt="Shampo Manos"
        />
        <div className={styles.shampo_manos_textos}>
          <h2>Shampoo para Manos</h2>
          <p>
            El shampoo para manos o jabón líquido esta formulado para el lavado
            de manos. Su exclusiva fórmula equilibra limpieza y desengrasa con
            humectación para no resecar la piel y dejarla suave con una
            agradable fragancia recomendada para una ideal higiene, realizando
            una desinfección profunda y protegiéndola de agentes extraños.
          </p>
          <Image
            src={'/images/Productos/LogosAromas/colores_shampoparamanos.png'}
            width={420}
            height={120}
            alt="Shampo Manos"
          />
        </div>
      </section>
      <section className={styles.cloro_liquido} id="cloro_liquido">
        <Image
          className={styles.cloro_liquido_logo}
          src={'/images/Productos/LogosAromas/cloroliquidopicinas.png'}
          width={500}
          height={500}
          alt="Cloro Liquido"
        />
        <Image
          className={styles.cloro_liquido_productos}
          src={'/images/Productos/Layers/cloroLiquidopicinas.png'}
          width={1200}
          height={850}
          alt="Cloro Liquido"
        />
        <div className={styles.cloro_liquido_textos}>
          <h2>Cloro Líquido para Piscinas</h2>
          <p>
            Hipoclorito de sodio con una concentración de 80 grs cl/lts. para
            mantener una piscina de natación impecable por toda la temporada,
            utilizando cloro evita la presencia de bacterias en su piscina. No
            debe desbalancearse ni contaminarse, ayuda a controlar el ph.
          </p>
        </div>
      </section>
      <section className={styles.cera_acrilica} id="cera_acrilica">
        <Image
          className={styles.cera_acrilica_logo}
          src={'/images/Productos/LogosAromas/ceraacrilica.png'}
          width={500}
          height={500}
          alt="Cera Acrilica"
        />
        <Image
          className={styles.cera_acrilica_productos}
          src={'/images/Productos/Layers/CeraAcrilica.png'}
          width={1000}
          height={850}
          alt="Cera Acrilica"
        />
        <div className={styles.cera_acrilica_textos}>
          <h2>Cera Acrílica</h2>
          <p>
            Otorga a sus pisos brillo instantáneo y resistente. Fácil de
            aplicar, dejando un agradable perfume. Utilizar con carro o mopa.
            Aplicar puro o diluido hasta una tercera parte sobre el piso.
          </p>
          <Image
            src={'/images/Productos/LogosAromas/colores_ceraacrilica.png'}
            width={420}
            height={120}
            alt="Cera Acrilica"
          />
        </div>
      </section>
      <section
        className={styles.liquido_desinfectante}
        id="liquido_desinfectante"
      >
        <Image
          className={styles.liquido_desinfectante_logo}
          src={'/images/Productos/LogosAromas/liquidodesinfectante.png'}
          width={500}
          height={500}
          alt="Liquido Desinfectante"
        />
        <Image
          className={styles.liquido_desinfectante_productos}
          src={'/images/Productos/Layers/LiquidoDesinfectante.png'}
          width={850}
          height={850}
          alt="Liquido Desinfectante"
        />
        <div className={styles.liquido_desinfectante_textos}>
          <h2>Líquido Desinfectante</h2>
          <p>
            Poderoso líquido desinfectante, apto para superficies lavables en el
            interior y exterior de su vivienda, expuestas a diferentes tipos de
            gérmenes. Está específicamente formulado para que no lo afecten las
            aguas duras. Dado que la formulación del producto no incluye
            hidrocarburos de ningún tipo, ni solventes aromáticos se reduce
            notablemente el impacto del producto al medio ambiente.
          </p>
          <Image
            src={'/images/Productos/productonocivo.png'}
            width={120}
            height={50}
            alt="Nocivo"
          />
        </div>
      </section>
      <section className={styles.alcohol_gel} id="alcohol_gel">
        <Image
          className={styles.alcohol_gel_logo}
          src={'/images/Productos/LogosAromas/AlcoholEnGel.png'}
          width={500}
          height={500}
          alt="Alcohol Gel"
        />
        <Image
          className={styles.alcohol_gel_productos}
          src={'/images/Productos/Layers/alcoholengel.png'}
          width={850}
          height={850}
          alt="Alcohol Gel"
        />
        <div className={styles.alcohol_gel_textos}>
          <h2>Alcohol en Gel</h2>
          <p>
            Gel antibacterial sin acción terapéutica, a base de alcohol etílico,
            incoloro y sin perfume. Fórmula con alto contenido de alcohol que
            elimina eficazmente el 99.9% de bacterias y gérmenes sin necesidad
            de enjuague. Su textura en gel permite una aplicación fácil y
            rápida, dejando las manos limpias y frescas sin sensación pegajosa.
            Enriquecido con agentes humectantes para proteger la piel, es ideal
            para el uso diario en el hogar, la oficina o en movimiento.
          </p>
        </div>
      </section>
    </div>
  );
};

export default Productos;
